---
config:
  layout: dagre
  look: neo
---
flowchart LR
    CUST["Заказчик"] -- Заявка --> P1("1 Принимать заявки")
    CUST -- Документы для оцифровки --> P4("4 Оцифровывать и маркировать документы")
    CUST -- Подписанный заказчиком договор --> P3("3 Оформлять договор и обрабатывать оплату")
    DISP["Диспетчер"] -- Фиксация заявки --> P1
    DISP -- Информация о приёме документа --> P1
    GDIR["Генеральный директор"] -- Детали заказа --> P2("2 Рассчитывать смету, план и спецификацию")
    GDIR -- "Архивно-коммерческое предложение с реквизитами" --> P3
    EST["Отдел расчётов"] -- Смета --> DB2[("2 Сметы")]
    ACCT["Бухгалтерия"] -- План и спецификация --> DB3[("3 Планы и спецификации")]
    LAW["Юрист"] -- Подписанный юристом черновик договора --> P3
    BANK["Банк"] -- Подтверждение платежа --> P3
    ALDA["Архив АЛЬДА"] -- Оцифрованные документы --> P4
    P3 -- "Архивно-коммерческое предложение с реквизитами" --> CUST
    P3 -- Заключённый договор --> DB4[("4 Договоры")]
    P3 -- Подписанный юристом черновик договора --> CUST
    P5("5 Мониторить и формировать отчёты") -- Статус заявки --> DISP
    P5 -- Оповещение о сроке --> DISP
    P1 -- Заявка --> DB1[("1 Заявки")]
    DB1 -- Заявка --> GDIR & P5
    DB2 -- Смета --> P2 & P5 & ACCT
    DB3 -- План и спецификация --> P5 & P2
    P2 -- Смета --> GDIR
    P2 -- План и спецификация --> GDIR
    P3 -- Черновик договора на проверку --> LAW
    DB4 -- Заключённый договор --> P5
    P4 -- Оцифрованные маркированные документы --> DB5[("5 Оцифрованные маркированные документы")]
    P4 -- Документы для оцифровки --> ALDA
    DB5 -- Метаданные документов --> P5
    DB6[("6 Отчёты")] <-- Отчёты --> P5
