---
config:
  layout: elk
---
flowchart LR
    CUST["Заказчик"] -- Заявка --> P0("Автоматизировать процессы архивации и оцифровки")
    CUST -- Документ для оцифровки --> P0
    CUST -- Подписанный заказчиком договор --> P0
    DISP["Диспетчер"] -- Фиксация заявки --> P0
    DISP -- Информация о приёме документа --> P0
    GDIR["Генеральный директор"] -- Детали заказа --> P0
    GDIR -- "Архивно-коммерческое предложение с реквизитами" --> P0
    EST["Отдел расчётов"] -- Смета --> P0
    ACCT["Бухгалтерия"] -- План и спецификация --> P0
    LAW["Юрист"] -- Подписанный юристом черновик договора --> P0
    BANK["Банк"] -- Подтверждение платежа --> P0
    ALDA["Архив АЛЬДА"] -- Оцифрованные документы --> P0
    P0 -- "Архивно-коммерческое предложение с реквизитами" --> CUST
    P0 -- Подписанный юристом черновик договора --> CUST
    P0 -- Статус заявки --> DISP
    P0 -- Оповещение о сроке --> DISP
    P0 -- Смета --> GDIR & ACCT
    P0 -- План и спецификация --> GDIR
    P0 -- Детали заказа --> EST
    P0 -- Черновик договора на проверку --> LAW
    P0 -- Документы для оцифровки --> ALDA
